In [3]:
import numpy as np

1. Create a 5X2 integer array from a range between 100 to
200 such that the difference between each element is 10

In [2]:
print ("Create 5x2 integer range between 100 to 200")
sa = np.arange(100,200,10)
sa = sa.reshape(5,2)
print(sa)

Create 5x2 integer range between 100 to 200
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Write a NumPy program to create a 3x3x3 array filled
with arbitrary values and find the minimum and maximum
values.


In [ ]:
SampleA = np.random.random([3,3,3])
print(SampleA)
print("-------------------")
print("Minimum Value : ",SampleA.min())
print("-----------------")
print("Maximum Value : ",SampleA.max())

[[[0.09860706 0.46283371 0.80095953]
  [0.21738563 0.34815141 0.30023045]
  [0.78611328 0.73050742 0.77372311]]

 [[0.82552072 0.89393051 0.90388155]
  [0.26115686 0.29183509 0.45573254]
  [0.63315329 0.0853799  0.96494706]]

 [[0.42530943 0.14836844 0.4464967 ]
  [0.25885102 0.28282309 0.51365886]
  [0.58160449 0.24653806 0.8932476 ]]]
-------------------
Minimum Value :  0.08537990315350918
-----------------
Maximum Value :  0.9649470572563775


3. Write a NumPy program to create a 5x5 zero matrix
with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


4. Given an array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
i) Extract all odd numbers from arr
ii) Replace all odd numbers in arr with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = []

for i in arr:
  if i%2 == 0:
    print(f"{i} its an even number")
  else:
    print(f"{i} odd number")
    odd.append(i)

print(np.array(odd))
odd = np.array(odd)-1
print(np.array(odd))

print("After Replacement : ",odd)

0 its an even number
1 odd number
2 its an even number
3 odd number
4 its an even number
5 odd number
6 its an even number
7 odd number
8 its an even number
9 odd number
[1 3 5 7 9]
[0 2 4 6 8]
After Replacement :  [0 2 4 6 8]


5. Write a NumPy program to create a 3x3 identity matrix,
i.e. diagonal elements are 1,the rest are 0.

In [ ]:
x = np.diag([1,1,1])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


6. Write a NumPy program to convert an array to a float
type.

In [ ]:
x2 = [1,2,3,4]
print(x2)
y = np.asfarray(x2)
print("Array converted to float : ")
print(y)


[1, 2, 3, 4]
Array converted to float : 
[1. 2. 3. 4.]


7. Write a NumPy program to generate five random
numbers from the normal distribution.

In [ ]:
x3 = np.random.normal (size = 5)
print(x3)


[-0.38130768  0.24318708  0.51589788 -0.59179507 -1.53396057]


8. Following is the input NumPy array delete column two
and insert following new column in its place.


sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,
66]])


newColumn = numpy.array([[10,10,10]])

In [ ]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray)

print("----------------")
print("After delete")
sampleArray = np.delete(sampleArray,1,axis=1)
print(sampleArray)

print("----------------")
print("After Insert")
sampleArray = np.insert(sampleArray,1,newColumn,axis=1)
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
----------------
After delete
[[34 73]
 [82 12]
 [53 66]]
----------------
After Insert
[[34 10 73]
 [82 10 12]
 [53 10 66]]


9. Write a NumPy program to compute the multiplication
of two given matrices.

In [ ]:
mat1 = [1,2],[3,4]
mat2 = [4,3],[2,1]
print(mat1)
print(mat2)
print("-----")
s = np.multiply(mat1,mat2)
s

([1, 2], [3, 4])
([4, 3], [2, 1])
-----


array([[4, 6],
       [6, 4]])

10. Write a NumPy program to create a random vector of
size 10 and sort it.

In [17]:
x = np.random.random(10)
print("X value")
print(x)

print("-------------  ")
print("Sorted X Value")
x.sort()
print(x)

X value
[0.66426817 0.23792484 0.82646223 0.47148495 0.26679201 0.57908916
 0.07579241 0.66758798 0.54020534 0.90520105]
-------------
Sorted X Value
[0.07579241 0.23792484 0.26679201 0.47148495 0.54020534 0.57908916
 0.66426817 0.66758798 0.82646223 0.90520105]


11. Write a NumPy program to compute the covariance
matrix of two arrays.

In [18]:
x = np.array([0,1,2])
y = np.array([-2,-1,0])
z = np.cov(x,y)
print(z)

[[1. 1.]
 [1. 1.]]


12.Create a 4X2 integer array and Prints its :

i)The shape of an array.

ii) Array dimensions.

iii) The Length of each element of the array in bytes

In [27]:
x = np.empty([4,2], dtype = int)
print(x)
print("Shape: ",x.shape)
print("Dimension :", x.ndim)
print("Length in bytes:", x.itemsize)

[[           50801856      13683765805067]
 [1040894463876887040         66337112064]
 [8390326431219980890 8388353894424474719]
 [8318823012416185902      18083581027118]]
Shape:  (4, 2)
Dimension : 2
Length in bytes: 8


13. Write a NumPy program to concatenate element-wise
two arrays of string.

In [35]:
x1 = np.array(['Fruit', 'Color'],dtype= str)
x2 = np.array([' Mango',' Yellow'],dtype = str)
print(x1)
print(x2)
x3 = np.char.add(x1,x2)
print(x3)
x3.shape
x3

['Fruit' 'Color']
[' Mango' ' Yellow']
['Fruit Mango' 'Color Yellow']


array(['Fruit Mango', 'Color Yellow'], dtype='<U12')

14. Write a NumPy program to 

capitalize the first letter,

lowercase, 

uppercase, 

swapcase, 

title-case 

of all the elements of a given array.

In [42]:
x4 = np.array(['deepak','virar','india'],dtype=str)
print(x4)
print("Capitalize", np.char.capitalize(x4))
print("Lower Case: ", np.char.lower(x4))
print("Upper Case: ", np.char.upper(x4))
print("Swap Case: ", np.char.swapcase(x4))
print("Titled Case",np.char.title(x4))

['deepak' 'virar' 'india']
Capitalize ['Deepak' 'Virar' 'India']
Lower Case:  ['deepak' 'virar' 'india']
Upper Case:  ['DEEPAK' 'VIRAR' 'INDIA']
Swap Case:  ['DEEPAK' 'VIRAR' 'INDIA']
Titled Case ['Deepak' 'Virar' 'India']


15. Write a NumPy program to convert a given array into
a list.

In [44]:
x5 = ([1,2],[3,4])
b = np.array(x5)
b1 = b.tolist()
print(b1)

[[1, 2], [3, 4]]


16. Write a NumPy program to compute the 

sum of all elements, 

sum of each column and 

sum of each row of a given array.

In [52]:
x6 = np.array([[1,2],[3,4]])
print(x6)
print("Sum: ",np.sum(x6))
print("Sum of Column: ",np.sum(x6,axis=0))
print("Sum of Rows: ",np.sum(x6,axis=1))

[[1 2]
 [3 4]]
Sum:  10
Sum of Column:  [4 6]
Sum of Rows:  [3 7]


17. Write a NumPy program to create a random 10x4 array and 

extract the first five rows of the array and 

store them into a variable.

In [64]:
x7 = np.random.rand(10,4)
print(x7)
print("----- First 5 Rows-----")
y = x7[ :5]
print(y)

[[0.75581573 0.4745236  0.57269579 0.47648989]
 [0.87528533 0.45840564 0.25716616 0.60672158]
 [0.32552138 0.82954271 0.59694736 0.17001385]
 [0.57979118 0.61018405 0.71020791 0.88850287]
 [0.46670692 0.48911477 0.42571658 0.0177804 ]
 [0.64294561 0.68280388 0.05886706 0.33764582]
 [0.04404812 0.83024006 0.60022969 0.59003079]
 [0.40621775 0.6105587  0.12029356 0.59768247]
 [0.47075677 0.7669968  0.41934462 0.67922922]
 [0.29891311 0.47828811 0.02122541 0.69320741]]
----- First 5 Rows-----
[[0.75581573 0.4745236  0.57269579 0.47648989]
 [0.87528533 0.45840564 0.25716616 0.60672158]
 [0.32552138 0.82954271 0.59694736 0.17001385]
 [0.57979118 0.61018405 0.71020791 0.88850287]
 [0.46670692 0.48911477 0.42571658 0.0177804 ]]


18. Write a NumPy program to get the unique elements of
a 1D and 2D array.

In [69]:
x8 = np.array([10,10,10,20,20,30,30,30])
print("Unique Number: ",np.unique(x8))

x9 = np.array([[10,30],[30,40]])
print("Unique Number: ",np.unique(x9))

Unique Number:  [10 20 30]
Unique Number:  [10 30 40]
